### PR TITLE
Added Serial

### PR DESCRIPTION
**Pull request by Odianosen25**

### CODE REVIEW

**Comment by jabdoa2** [comment]
Can you change the existing files instead of readding them. The delta/changes should be only your new functions.

**Comment by Odianosen25** [comment]
Hello @jabdoa2,

I am sorry I don't understand what you meant. This is my second ever PR, and the first one, well was a bit of a mess. What do you mean by "reading them"?

**Comment by jabdoa2** [comment]
Sorry I'm currently on my mobile. Should be "re-adding". The PR looks like you added apigpio.py a second time to the root folder of the repository. Try to change the existing one in the apigpio folder. That should create a very minimal change.

**Comment by Odianosen25** [comment]
Oh ok, will try that now thanks

**Comment by Odianosen25** [comment]
Hello @jabdoa2, Sorry been finding it difficult for me to figure out how to do what you want. I think the only option I have is to try close this PR and redo it again.

You fine with that?

Regards

**Comment by jabdoa2** [comment]
Sure create as many as you need. Basically this is the process:

- Check it out
- Create a branch
- Change files in place
- Commit
- Push
- Create PR

**Comment by Odianosen25** [comment]
Ok will try that

**Comment by Odianosen25** [comment]
Took a while, but I think I finally cracked it :)

**Pull request closed without merging**
